[tool.poetry]
name = "micrlhf-progress"
version = "0.0.1"
description = ""
authors = ["\"n\""]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sentencepiece = "^0.2.0"
penzai = "^0.1.0"
jax = {version = "^0.4.26", extras = ["tpu"]}

[[tool.poetry.source]]
name = "google-libtpu"
url = "https://storage.googleapis.com/jax-releases/libtpu_releases.html"
priority = "supplemental"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
